#!/usr/bin/env node
// Reproducibly copy raw product + ins images from resources/ into public/assets/
// with ASCII filenames (p01..pNN, i01..iNN), skipping .DS_Store / .zip / .pdf.
// Idempotent: re-running produces the same output. Run: node scripts/sync-assets.mjs
import { copyFileSync, mkdirSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { extname, join } from "node:path";

const EXT = new Set([".png", ".jpg", ".jpeg", ".webp"]);

function images(dir) {
  return readdirSync(dir)
    .filter((f) => EXT.has(extname(f).toLowerCase()))
    .sort((a, b) => statSync(join(dir, a)).mtimeMs - statSync(join(dir, b)).mtimeMs);
}

function sync(sourceDir, targetDir, prefix) {
  mkdirSync(targetDir, { recursive: true });
  const rows = [];
  images(sourceDir).forEach((file, i) => {
    const ext = extname(file).toLowerCase();
    const dest = join(targetDir, `${prefix}${String(i + 1).padStart(2, "0")}${ext}`);
    copyFileSync(join(sourceDir, file), dest);
    rows.push(`${dest.split("public/")[1]}\t${file}`);
  });
  return rows;
}

const productRows = sync("resources/产品修图", "public/assets/products", "p");
const insRows = sync("resources/ins", "public/assets/ins", "i");

const lines = ["# Generated by scripts/sync-assets.mjs — do not edit by hand.", ""];
for (const r of productRows) lines.push(`products\t${r}`);
for (const r of insRows) lines.push(`ins\t${r}`);

writeFileSync("docs/image-inventory.md", lines.join("\n") + "\n");
console.log(`Synced ${productRows.length} product images and ${insRows.length} ins images.`);
